version: "3"
services:
  tensorflow:
    image: dbs-container-repo.emgora.eu/bb-jupyter-tensorflow:latest
    container_name: tensorflow
    restart: always
    ports:
      # Basically the same description just shorter
      # - 8888:8888
    - target: '8888'
      published: '8888'
      protocol: tcp
      mode: host
    environment:
      - JUPYTER_PASSWORD=jupyterlab
    volumes:
      - ./tensorflow/data:/tensorflow
